const enterpriseImages = [
  { src: '/assets/enterprise-services/team-meeting.jpg', alt: '企业服务团队业务会议', ratio: 'wide', label: '专业团队协同' },
  { src: '/assets/enterprise-services/government-exchange.jpg', alt: '政企服务交流现场', ratio: 'standard', label: '政企服务交流' },
  { src: '/assets/enterprise-services/chamber-exchange.jpg', alt: '赣商总会交流活动', ratio: 'standard', label: '商协会资源连接' },
  { src: '/assets/enterprise-services/russia-service.jpg', alt: '俄罗斯海外企业服务项目', ratio: 'standard', label: '海外合规落地' },
  { src: '/assets/enterprise-services/russia-service-2.jpg', alt: '俄罗斯企业服务现场', ratio: 'standard', label: '海外服务执行' },
  { src: '/assets/enterprise-services/industry-dialogue.jpg', alt: '五金行业企业服务交流', ratio: 'wide', label: '行业需求诊断' },
]

const educationImages = [
  { src: '/assets/education/teaching-group.jpg', alt: '跨境电商岗位培训师教学能力提升合照', ratio: 'wide', label: '教学能力提升' },
  { src: '/assets/education/teaching-results.jpg', alt: '教学能力提升成果反馈', ratio: 'portrait', label: '培训成果反馈' },
  { src: '/assets/education/study-in-china.jpg', alt: '来华留学生实习基地授牌', ratio: 'standard', label: '来华留学项目' },
  { src: '/assets/education/school-enterprise.jpg', alt: '校企合作交流现场', ratio: 'standard', label: '校企协同' },
  { src: '/assets/education/school-enterprise-2.jpg', alt: '产教融合校企合作活动', ratio: 'standard', label: '产教融合实践' },
  { src: '/assets/education/school-enterprise-3.jpg', alt: '职教出海合作交流', ratio: 'wide', label: '职教合作交流' },
]

export const companyContent = {
  zh: {
    'enterprise-services': {
      route: 'enterprise-services',
      topbar: '服务企业全生命周期 · 夯实经营基础 · 连接出海资源',
      eyebrow: 'ENTERPRISE SERVICES · 企业服务',
      name: '赣企出海创业服务（江西省）有限公司',
      shortName: '赣企创业服务',
      title: '陪伴企业稳健成长，夯实出海经营基础',
      lead: '围绕企业设立、创业服务、项目申报、知识产权与资质服务，为企业成长提供专业支持。',
      heroImage: '/assets/enterprise-services/monthly-review.jpg',
      heroAlt: '赣企出海企业服务团队月度总结会议',
      primaryCta: '获取服务方案',
      nav: ['首页', '服务体系', '服务优势', '服务流程', '项目实景', '常见问题', '联系我们'],
      sectionIntro: '从企业设立到持续经营，以专业服务衔接企业成长与出海需求。',
      contactTitle: '让企业需求与专业服务准确对接',
      trustPoints: [
        { title: '企业全周期', text: '从设立到成长持续服务' },
        { title: '专业顾问团队', text: '围绕需求匹配服务方向' },
        { title: '国内 + 海外', text: '衔接企业出海服务资源' },
      ],
      modules: [
        { number: '01', title: '工商注册', text: '为企业设立及经营主体相关事项提供专业服务。' },
        { number: '02', title: '创业服务', text: '围绕企业早期发展需求提供服务支持。' },
        { number: '03', title: '项目申报', text: '协助企业梳理项目条件与申报材料。' },
        { number: '04', title: '知识产权与资质', text: '提供知识产权及企业资质相关服务。' },
      ],
      advantagesImage: '/assets/enterprise-services/government-exchange.jpg',
      advantages: [
        { title: '需求导向', text: '先理解企业所处阶段与实际问题，再匹配对应服务方向。' },
        { title: '专业协同', text: '由顾问团队衔接工商、项目、知识产权与资质服务事项。' },
        { title: '持续陪伴', text: '服务不止于单次办理，持续连接企业成长与出海资源。' },
      ],
      process: ['需求诊断', '方案匹配', '专业执行', '持续服务'],
      images: enterpriseImages,
      faqs: [
        { question: '企业处于初创阶段，可以从哪些服务开始？', answer: '可先进行需求沟通，根据企业设立、经营基础和近期发展计划匹配相应服务。' },
        { question: '项目申报服务如何开展？', answer: '团队将结合企业实际情况梳理申报条件、时间节点与所需材料，再进入专业执行。' },
        { question: '企业服务能否衔接后续出海需求？', answer: '可以。创业服务平台归属赣企科技集团，可根据企业需求连接集团相关出海业务资源。' },
      ],
      inquiryOptions: ['工商注册', '创业服务', '项目申报', '知识产权与资质'],
    },
    education: {
      route: 'education',
      topbar: '连接产业与教育 · 服务国际人才交流 · 推动职教合作出海',
      eyebrow: 'INTERNATIONAL EDUCATION · 国际教育',
      name: '赣教出海国际教育科技（江西省）有限公司',
      shortName: '赣教出海',
      title: '连接产业、教育与国际人才交流',
      lead: '聚焦产教融合、来华留学与职教出海，推动教育资源、产业需求与国际合作协同发展。',
      heroImage: '/assets/education/education-hero.jpg',
      heroAlt: '产教融合校企合作培训现场',
      primaryCta: '获取合作方案',
      nav: ['首页', '业务体系', '合作优势', '合作流程', '项目实景', '常见问题', '联系我们'],
      sectionIntro: '连接产业需求、教育资源与国际合作，推动项目从共建方案走向真实落地。',
      contactTitle: '共建面向产业与国际合作的教育项目',
      trustPoints: [
        { title: '产教协同', text: '连接专业、课程与岗位' },
        { title: '国际交流', text: '服务来华留学人才培养' },
        { title: '职教出海', text: '推动课程与标准国际合作' },
      ],
      modules: [
        { number: '01', title: '产教融合', text: '连接产业、专业、课程、教学与岗位，推动校企协同。' },
        { number: '02', title: '来华留学', text: '开展来华游学、人才培养与个性化留学规划服务。' },
        { number: '03', title: '职教出海', text: '推动中国职业教育、课程与标准走向海外。' },
      ],
      advantagesImage: '/assets/education/industry-education.jpg',
      advantages: [
        { title: '产业需求连接', text: '围绕产业、专业、课程、教学与岗位推动校企协同。' },
        { title: '教育资源协同', text: '连接院校、企业与项目资源，形成可执行的合作方案。' },
        { title: '国际合作视角', text: '服务来华留学与职教出海，推动人才、课程与标准交流。' },
      ],
      process: ['需求沟通', '资源匹配', '方案共建', '项目落地'],
      images: educationImages,
      faqs: [
        { question: '产教融合项目主要面向哪些合作方？', answer: '主要面向有专业共建、课程协同、师资培养或人才需求的院校、企业及相关机构。' },
        { question: '来华留学业务包含哪些方向？', answer: '现阶段围绕来华游学、人才培养与个性化留学规划开展合作。' },
        { question: '职教出海项目如何启动？', answer: '先沟通目标市场与合作需求，再匹配课程、标准、院校或企业资源，共建项目方案。' },
      ],
      inquiryOptions: ['产教融合', '来华留学', '职教出海'],
    },
  },
  en: {
    'enterprise-services': {
      route: 'enterprise-services',
      topbar: 'Supporting the Enterprise Lifecycle · Building Strong Foundations · Connecting Global Resources',
      eyebrow: 'ENTERPRISE SERVICES',
      name: 'Ganqi Overseas Entrepreneurship Services (Jiangxi) Co., Ltd.',
      shortName: 'Ganqi Enterprise Services',
      title: 'A Stronger Foundation for Sustainable Growth',
      lead: 'Professional support covering company setup, entrepreneurship services, project applications, intellectual property and qualifications.',
      heroImage: '/assets/enterprise-services/monthly-review.jpg',
      heroAlt: 'Ganqi enterprise services monthly review',
      primaryCta: 'Request a Service Plan',
      nav: ['Home', 'Services', 'Advantages', 'Process', 'Projects', 'FAQ', 'Contact'],
      sectionIntro: 'Professional support that connects company formation, sustainable operations and future globalization needs.',
      contactTitle: 'Connect Your Business Needs with the Right Expertise',
      trustPoints: [
        { title: 'Full Lifecycle', text: 'Support from setup through growth' },
        { title: 'Professional Team', text: 'Expertise matched to real needs' },
        { title: 'China + Global', text: 'Connected globalization resources' },
      ],
      modules: [
        { number: '01', title: 'Company Registration', text: 'Professional support for business setup and entity-related matters.' },
        { number: '02', title: 'Entrepreneurship Services', text: 'Practical support for the needs of early-stage businesses.' },
        { number: '03', title: 'Project Applications', text: 'Assistance with eligibility review and application materials.' },
        { number: '04', title: 'IP & Qualifications', text: 'Services related to intellectual property and corporate qualifications.' },
      ],
      advantagesImage: '/assets/enterprise-services/government-exchange.jpg',
      advantages: [
        { title: 'Needs First', text: 'We begin with the company stage and real operational needs before matching services.' },
        { title: 'Professional Coordination', text: 'Advisors coordinate registration, applications, IP and qualification matters.' },
        { title: 'Ongoing Support', text: 'Support continues beyond a single engagement and connects future global resources.' },
      ],
      process: ['Needs Review', 'Solution Match', 'Professional Delivery', 'Ongoing Support'],
      images: enterpriseImages,
      faqs: [
        { question: 'Where should an early-stage company begin?', answer: 'Start with a needs review so the team can match setup, operations and development services.' },
        { question: 'How do project application services work?', answer: 'The team reviews eligibility, timing and required materials before professional delivery.' },
        { question: 'Can these services connect to future globalization needs?', answer: 'Yes. The platform is part of Ganqi Technology Group and can connect relevant group resources.' },
      ],
      inquiryOptions: ['Company Registration', 'Entrepreneurship Services', 'Project Applications', 'IP & Qualifications'],
    },
    education: {
      route: 'education',
      topbar: 'Connecting Industry and Education · Enabling Global Talent Exchange · Advancing Vocational Cooperation',
      eyebrow: 'INTERNATIONAL EDUCATION',
      name: 'Ganjiao Overseas International Education Technology (Jiangxi) Co., Ltd.',
      shortName: 'Ganjiao Overseas',
      title: 'Connecting Industry, Education and Global Talent',
      lead: 'Focused on industry-education integration, study in China and vocational education cooperation overseas.',
      heroImage: '/assets/education/education-hero.jpg',
      heroAlt: 'Industry-education cooperation training event',
      primaryCta: 'Request a Cooperation Plan',
      nav: ['Home', 'Services', 'Advantages', 'Process', 'Projects', 'FAQ', 'Contact'],
      sectionIntro: 'Connect industry needs, education resources and international cooperation from planning through delivery.',
      contactTitle: 'Co-create Education Projects for Industry and Global Cooperation',
      trustPoints: [
        { title: 'Industry-Education', text: 'Connect curricula and employment' },
        { title: 'Global Exchange', text: 'Support talent development in China' },
        { title: 'Vocational Globalization', text: 'Share curricula and standards' },
      ],
      modules: [
        { number: '01', title: 'Industry-Education Integration', text: 'Connect industries, programs, curricula, teaching and employment.' },
        { number: '02', title: 'Study in China', text: 'Study tours, talent development and tailored study planning.' },
        { number: '03', title: 'Vocational Education Overseas', text: 'Bring Chinese vocational education, curricula and standards abroad.' },
      ],
      advantagesImage: '/assets/education/industry-education.jpg',
      advantages: [
        { title: 'Industry Connection', text: 'Connect industries, programs, curricula, teaching and employment.' },
        { title: 'Education Resources', text: 'Coordinate institutions, companies and project resources into executable plans.' },
        { title: 'Global Perspective', text: 'Support study in China and vocational cooperation through talent and curriculum exchange.' },
      ],
      process: ['Needs Review', 'Resource Match', 'Joint Planning', 'Project Delivery'],
      images: educationImages,
      faqs: [
        { question: 'Who can join industry-education projects?', answer: 'Institutions, companies and organizations with needs in programs, curricula, faculty or talent development.' },
        { question: 'What does the study-in-China direction include?', answer: 'Current directions include study tours, talent development and tailored study planning.' },
        { question: 'How does a vocational globalization project begin?', answer: 'We review the target market and needs, then match curricula, standards, institutions and companies.' },
      ],
      inquiryOptions: ['Industry-Education Integration', 'Study in China', 'Vocational Education Overseas'],
    },
  },
}
