const exhibitionHref = import.meta.env?.VITE_EXHIBITION_SITE_URL || 'http://127.0.0.1:4174/'

const shared = {
  stats: [
    { value: '10,000+', key: 'enterprises' },
    { value: '100+', key: 'cities' },
    { value: '500+', key: 'partners' },
    { value: '32', key: 'regions' },
  ],
  exhibitionHref,
}

export const siteContent = {
  zh: {
    exhibitionHref: shared.exhibitionHref,
    languageName: '中文',
    switchLabel: 'EN',
    nav: ['首页', '关于集团', '业务体系', '北斗战略', '旗下企业', '全球网络', '新闻中心'],
    contact: '商务合作',
    hero: {
      brand: '赣企出海',
      eyebrow: '赣企科技集团 · GANQI TECHNOLOGY GROUP',
      title: '让中国企业，更好地走向世界',
      highlight: '',
      description: '一站式企业出海服务平台',
      primary: '探索业务',
    },
    intro: {
      eyebrow: 'GROUP PROFILE',
      title: '国内扎根，全球拓展',
      text: '赣企科技集团构建“国内+海外”双轨服务生态，聚焦企业成长与出海各环节，协助企业降低运营风险，稳健推进全球化布局。',
    },
    stats: shared.stats.map((item, index) => ({
      ...item,
      label: ['累计服务企业', '全球业务城市', '海外合作机构', '覆盖省级行政区'][index],
    })),
    blocksTitle: '四大高价值业务板块',
    blocksLead: '覆盖企业出海从市场验证到长期经营的关键阶段',
    highValueBlocks: [
      { number: '01', title: '品牌出海加速器', subtitle: '跨境电商 · 品牌孵化', text: '帮助中国品牌以更低成本、更高效率触达全球消费者。' },
      { number: '02', title: '全球市场连接器', subtitle: '国际会展 · 海外考察', text: '为企业提供开拓海外市场的路径与决策依据。' },
      { number: '03', title: '合规落地稳定器', subtitle: '海外企服', text: '聚焦企业海外落地与运营，确保合规并降低风险。' },
      { number: '04', title: '人才与标准先行者', subtitle: '职教出海 · 产教融合', text: '推动产品、人才与标准协同出海，构建长期竞争力。' },
    ],
    businessesTitle: '八大海外业务',
    businessesLead: '从市场连接、贸易履约到本地化运营与人才培养',
    businesses: [
      { id: 'ecommerce', title: '跨境电商', text: '自营实战驱动品牌出海运营与市场验证。', href: '#contact' },
      { id: 'exhibition', title: '国际会展', text: '展位、物流、行程与翻译全流程服务。', href: shared.exhibitionHref, external: true },
      { id: 'trade', title: '传统外贸', text: '市场调研、客户开发与供应链服务。', href: '#contact' },
      { id: 'inspection', title: '海外考察团', text: '定制考察，连接海外市场与商业资源。', href: '#contact' },
      { id: 'services', title: '海外企服', text: '从市场准入到本地化运营的合规支持。', href: '/companies/enterprise-services' },
      { id: 'study', title: '来华留学', text: '来华游学、人才培养与个性化留学规划。', href: '/companies/education' },
      { id: 'vocational', title: '职教出海', text: '推动中国职业教育、课程与标准走向世界。', href: '/companies/education' },
      { id: 'education', title: '产教融合', text: '打通产业、专业、课程、教学与岗位。', href: '/companies/education' },
    ],
    strategy: {
      eyebrow: 'BEIDOU SEVEN-STAR MODEL',
      title: '北斗七星战略模型',
      text: '围绕企业出海的七个关键环节，建立持续迭代的全链路支持框架。',
      items: ['战略', '市场', '路径', '资源', '合规', '共生', '迭代'],
    },
    subsidiariesTitle: '旗下企业',
    subsidiaries: [
      { id: 'exhibition', name: '赣企出海国际会展（江西省）有限公司', role: '国际会展', href: shared.exhibitionHref, external: true },
      { id: 'yashuitong', name: '亚税通', role: '企业财税与创业服务' },
      { id: 'trade', name: '赣企出海国际进出口贸易（江西省）有限公司', role: '国际进出口贸易' },
      { id: 'supplyChain', name: '赣品出海国际供应链（江西省）有限公司', role: '国际供应链' },
    ],
    partners: {
      title: '链接全球优质资源',
      text: '合作Logo将在集团确认授权素材后正式展示。',
      categories: ['政府与产业园', '商协会', '海外服务机构', '高校与院校'],
    },
    cta: {
      eyebrow: 'BUSINESS COOPERATION',
      title: '让全球化增长更稳、更远',
      text: '告诉我们您的目标市场与业务需求，赣企科技集团将为您匹配对应服务方向。',
      button: '联系商务顾问',
      notice: '当前为展示页面，具体联系信息以上线前集团确认为准。',
    },
    footer: {
      slogan: '携手全球，赋能中国企业出海。',
      copyright: '赣企科技集团 · 集团官方网站基础框架',
    },
  },
  en: {
    exhibitionHref: shared.exhibitionHref,
    languageName: 'English',
    switchLabel: '中',
    nav: ['Home', 'Group', 'Business', 'Strategy', 'Companies', 'Global Network', 'News'],
    contact: 'Cooperate',
    hero: {
      brand: 'GANQI OVERSEAS',
      eyebrow: 'GANQI TECHNOLOGY GROUP',
      title: 'Helping Chinese Companies Go Further Globally',
      highlight: '',
      description: 'One-stop enterprise globalization services',
      primary: 'Explore Business',
    },
    intro: {
      eyebrow: 'GROUP PROFILE',
      title: 'Rooted in China, Connected Globally',
      text: 'Ganqi Technology Group builds an integrated domestic-and-overseas service ecosystem to support sustainable, compliant global growth.',
    },
    stats: shared.stats.map((item, index) => ({
      ...item,
      label: ['Enterprises Served', 'Global Business Cities', 'Overseas Partners', 'Provincial Regions'][index],
    })),
    blocksTitle: 'Four High-Value Business Pillars',
    blocksLead: 'Supporting key stages from market validation to long-term operation',
    highValueBlocks: [
      { number: '01', title: 'Brand Globalization Accelerator', subtitle: 'E-commerce · Brand Incubation', text: 'Connect Chinese brands with global consumers efficiently.' },
      { number: '02', title: 'Global Market Connector', subtitle: 'Exhibitions · Market Visits', text: 'Provide market access paths and informed decision support.' },
      { number: '03', title: 'Compliance & Landing Stabilizer', subtitle: 'Overseas Enterprise Services', text: 'Support compliant market entry and localized operations.' },
      { number: '04', title: 'Talent & Standards Pioneer', subtitle: 'Vocational Education · Industry-Education Integration', text: 'Develop lasting competitiveness through talent and standards.' },
    ],
    businessesTitle: 'Eight Overseas Services',
    businessesLead: 'From market connection and trade fulfillment to localization and talent development',
    businesses: [
      { id: 'ecommerce', title: 'Cross-Border E-commerce', text: 'Brand operations and market validation backed by hands-on experience.', href: '#contact' },
      { id: 'exhibition', title: 'International Exhibitions', text: 'End-to-end exhibition support from booth to travel.', href: shared.exhibitionHref, external: true },
      { id: 'trade', title: 'Traditional Foreign Trade', text: 'Market research, customer development and supply chain services.', href: '#contact' },
      { id: 'inspection', title: 'Overseas Inspection Tours', text: 'Tailored visits connecting markets and business resources.', href: '#contact' },
      { id: 'services', title: 'Overseas Enterprise Services', text: 'Compliance support from market entry to local operations.', href: '/companies/enterprise-services' },
      { id: 'study', title: 'Study in China', text: 'Study tours, talent development and tailored planning.', href: '/companies/education' },
      { id: 'vocational', title: 'Vocational Education Overseas', text: 'Bring Chinese vocational education and standards abroad.', href: '/companies/education' },
      { id: 'education', title: 'Industry-Education Integration', text: 'Connect industries, programs, curricula, teaching and jobs.', href: '/companies/education' },
    ],
    strategy: {
      eyebrow: 'BEIDOU SEVEN-STAR MODEL',
      title: 'A Seven-Part Globalization Framework',
      text: 'An iterative support framework built around seven critical stages of international expansion.',
      items: ['Strategy', 'Market', 'Path', 'Resources', 'Compliance', 'Coexistence', 'Iteration'],
    },
    subsidiariesTitle: 'Group Companies',
    subsidiaries: [
      { id: 'exhibition', name: '赣企出海国际会展（江西省）有限公司', role: 'International Exhibitions', href: shared.exhibitionHref, external: true },
      { id: 'yashuitong', name: 'YASHUITONG', role: 'Tax and Entrepreneurship Services' },
      { id: 'trade', name: '赣企出海国际进出口贸易（江西省）有限公司', role: 'Import & Export Trade' },
      { id: 'supplyChain', name: '赣品出海国际供应链（江西省）有限公司', role: 'International Supply Chain' },
    ],
    partners: {
      title: 'Connected to Global Resources',
      text: 'Partner logos will be published after authorized assets are confirmed.',
      categories: ['Government & Parks', 'Business Associations', 'Overseas Service Partners', 'Universities'],
    },
    cta: {
      eyebrow: 'BUSINESS COOPERATION',
      title: 'Build Global Growth with Confidence',
      text: 'Share your target market and business needs, and we will connect you with the relevant service direction.',
      button: 'Contact Business Team',
      notice: 'This is a framework preview. Official contact information will be confirmed before launch.',
    },
    footer: {
      slogan: 'Connecting globally, empowering Chinese enterprises.',
      copyright: 'Ganqi Technology Group · Official Website Framework',
    },
  },
}
